# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-16790-zhanghuimeng-ThinkPad-T430/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tfgg676-2L

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::enableVHDL2008 1
    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/ip/clk_wiz_0_2
    /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/ip/vio_0/hdl/verilog
    /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/ip/vio_0/hdl
  } /user_program/Xlinx/Vivado/2017.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      rt::read_verilog -include {
    /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/ip/clk_wiz_0_2
    /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/ip/vio_0/hdl/verilog
    /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/ip/vio_0/hdl
  } {
      /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/new/async.v
      /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/new/SEG7_LUT.v
    }
      rt::read_vhdl -lib xil_defaultlib {
      ./.Xil/Vivado-16790-zhanghuimeng-ThinkPad-T430/realtime/clk_wiz_0_stub.vhdl
      ./.Xil/Vivado-16790-zhanghuimeng-ThinkPad-T430/realtime/vio_0_stub.vhdl
    }
      rt::read_vhdl -lib xpm /user_program/Xlinx/Vivado/2017.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -vhdl2008 -lib xil_defaultlib {
      /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/new/include.vhd
      /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/new/EX.vhd
      /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/new/EX_to_MEM.vhd
      /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/new/HI_LO.vhd
      /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/new/ID.vhd
      /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/new/ID_to_EX.vhd
      /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/new/IF_to_ID.vhd
      /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/new/MEM.vhd
      /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/new/MEM_to_WB.vhd
      /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/new/PAUSE_CTRL.vhd
      /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/new/PC.vhd
      /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/new/REGISTERS.vhd
      /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/new/MIPS_CPU.vhd
      /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/new/MMU.vhd
      /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/new/SRAM_CONTROLL.vhd
      /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/new/SERIAL_CONTROLL.vhd
      /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/new/MEM_CONTROLL.vhd
      /home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.srcs/sources_1/new/CP0_REG.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-16790-zhanghuimeng-ThinkPad-T430/realtime/MIPS_CPU_synth.xdc
    rt::sdcChecksum
    set rt::top MIPS_CPU
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {/home/zhanghuimeng/Computer_Architecture/new/ThinpadProject/ThinpadProject.cache/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-16790-zhanghuimeng-ThinkPad-T430/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
