# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "Z:/Desktop/computer/ThinpadProject/ThinpadProject.runs/synth_1/.Xil/Vivado-3976-465A/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tfgg676-2L
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::enableVHDL2008 1
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog Z:/Desktop/computer/ThinpadProject/ThinpadProject.srcs/sources_1/new/SEG7_LUT.v
      rt::read_vhdl -vhdl2008 -lib xil_defaultlib {
      Z:/Desktop/computer/ThinpadProject/ThinpadProject.srcs/sources_1/new/include.vhd
      Z:/Desktop/computer/ThinpadProject/ThinpadProject.srcs/sources_1/new/EX.vhd
      Z:/Desktop/computer/ThinpadProject/ThinpadProject.srcs/sources_1/new/EX_to_MEM.vhd
      Z:/Desktop/computer/ThinpadProject/ThinpadProject.srcs/sources_1/new/HI_LO.vhd
      Z:/Desktop/computer/ThinpadProject/ThinpadProject.srcs/sources_1/new/ID.vhd
      Z:/Desktop/computer/ThinpadProject/ThinpadProject.srcs/sources_1/new/ID_to_EX.vhd
      Z:/Desktop/computer/ThinpadProject/ThinpadProject.srcs/sources_1/new/IF_to_ID.vhd
      Z:/Desktop/computer/ThinpadProject/ThinpadProject.srcs/sources_1/new/MEM.vhd
      Z:/Desktop/computer/ThinpadProject/ThinpadProject.srcs/sources_1/new/MEM_to_WB.vhd
      Z:/Desktop/computer/ThinpadProject/ThinpadProject.srcs/sources_1/new/PAUSE_CTRL.vhd
      Z:/Desktop/computer/ThinpadProject/ThinpadProject.srcs/sources_1/new/PC.vhd
      Z:/Desktop/computer/ThinpadProject/ThinpadProject.srcs/sources_1/new/REGISTERS.vhd
      Z:/Desktop/computer/ThinpadProject/ThinpadProject.srcs/sources_1/new/MIPS_CPU.vhd
      Z:/Desktop/computer/ThinpadProject/ThinpadProject.srcs/sources_1/new/MEM_CONTROLL.vhd
      Z:/Desktop/computer/ThinpadProject/ThinpadProject.srcs/sources_1/new/SRAM_CONTROLL.vhd
      Z:/Desktop/computer/ThinpadProject/ThinpadProject.srcs/sources_1/new/MMU.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top MIPS_CPU
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "Z:/Desktop/computer/ThinpadProject/ThinpadProject.runs/synth_1/.Xil/Vivado-3976-465A/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
